# Generated by Django 4.0.1 on 2022-02-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_buyer_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='pic',
        ),
        migrations.AlterField(
            model_name='seller',
            name='addressline1',
            field=models.CharField(blank=True, default=None, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='addressline2',
            field=models.CharField(blank=True, default=None, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='addressline3',
            field=models.CharField(blank=True, default=None, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
