# Generated by Django 3.2.7 on 2022-03-05 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_alter_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
    ]
